### ISSUE TITLE
Crash when creating a new world

### ISSUE THREAD

**Issue by benio1394** [Juuxel/WoodsAndMires#22]
https://pastebin.com/yqgaermF

This is on the newest version

**Comment by Sunconure11** [comment]
Can confirm the same crash on 1.19.2

https://pastebin.com/gSQPEVMY

**Comment by Sunconure11** [comment]
It's back, but this time, with BYG.

https://pastebin.com/1MjnYxjH

**Comment by Sunconure11** [comment]
https://pastebin.com/APBAQZHn
