### ISSUE TITLE
Pine Shrub will generate on any solid block instead of soil

### ISSUE THREAD

**Issue by TelepathicGrunt** [Juuxel/WoodsAndMires#4]
As I was testing Woods and Mire with my World Blender mod, it seems the Pine Shrub feature will generate on any block and so, it will place itself on Stone, Sand, and even on top of structures as well which could look weird. A simple check for soil-like blocks or material might be better?
![image](https://user-images.githubusercontent.com/40846040/100389906-bd5a2e00-2ffc-11eb-98f3-b3b859400dc2.png)

**Comment by Juuxel** [comment]
Yeah, that'd be better. I'll change that in the next update (which will come when I have time lol).
