### ISSUE TITLE
[Suggestion] Right click pine shrub log with pine leaves to add the leaves

### ISSUE THREAD

**Issue by saltyseadoggo** [Juuxel/WoodsAndMires#6]
Being able to right click the pine shrub log while holding pine leaves to set its `has_leaves` blockstate to `true`, therefore adding leaves to it, would be appreciated to allow us and other players to decorate with the 'leaf-logged' pine shrub log without needing to piston existing ones in from elsewhere in the world.

**Comment by Juuxel** [comment]
Added, thanks for the suggestion!
