### ISSUE TITLE
Pine door and trapdoor are missing

### ISSUE THREAD

**Issue by saltyseadoggo** [Juuxel/WoodsAndMires#7]
Pine planks cannot be made into their own unique door and trapdoor, the way that vanilla woods can.
I would be happy to make some textures for them that you can review in a pull request, if you are looking for such assistance.~

**Comment by Juuxel** [comment]
This and #8 are because I didn't have the time (because of ModFest) nor the creativity to make textures for them. 😄 I'll try to get them done in an update. (As well as fixing #5)

**Comment by Juuxel** [comment]
Added in WaM 2.
